# Generated by Django 3.2.5 on 2021-08-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('employed', 'employed'), ('unemployed', 'unemployed'), ('student', 'student')], max_length=10),
        ),
    ]
