# Generated by Django 3.2.5 on 2021-08-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockprices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
        ),
    ]
