# Generated by Django 3.2.5 on 2021-08-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_stockprices_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprices',
            name='date',
        ),
    ]
