# Generated by Django 3.2.5 on 2021-08-22 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprices',
            old_name='high',
            new_name='predicted_close',
        ),
        migrations.RemoveField(
            model_name='stockprices',
            name='low',
        ),
        migrations.AddField(
            model_name='stockprices',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
