# Generated by Django 3.2.5 on 2021-08-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0011_auto_20210822_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
