# Generated by Django 3.2.5 on 2021-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprices',
            name='open',
            field=models.FloatField(blank=True),
        ),
    ]
